owner: ShopHome76
repo: eventipix-status

sites:
  - name: Site public Eventipix
    url: https://eventipix.com

status-website:
  cname: status.eventipix.com
  name: État des services Eventipix
  introTitle: État des services Eventipix
  introMessage: Consultez la disponibilité des services Eventipix en temps réel.

  navbar:
    - title: État des services
      href: /
    - title: Eventipix
      href: https://eventipix.com
